In [381]:
import pandas as pd
import os
from langdetect import detect
import re
import os

In [382]:
kaggle = pd.read_csv('Kaggle/train.csv')
mcintire = pd.read_csv('McIntire/fake_or_real_news.csv')
reutersReal = pd.read_csv('Reuters/True.csv')
reutersFake = pd.read_csv('Reuters/Fake.csv')
buzzfeedReal = pd.read_csv('Buzzfeed_Politifact/BuzzFeed_real_news_content.csv')
buzzfeedFake = pd.read_csv('Buzzfeed_Politifact/BuzzFeed_fake_news_content.csv')
politiReal = pd.read_csv('Buzzfeed_Politifact/PolitiFact_real_news_content.csv')

In [383]:
kaggle.drop(['author', 'id'], axis=1, inplace=True)

In [384]:
kaggle.reset_index(drop=True, inplace=True)

In [385]:
fake_news_kaggle = kaggle[kaggle['label'] == 1]
real_news_kaggle = kaggle[kaggle['label'] == 0]

In [386]:
fake_news_kaggle

,title,text,label
0,House Dem Aide: We Didn’t Even See Comey’s Let...,House Dem Aide: We Didn’t Even See Comey’s Let...,1
2,Why the Truth Might Get You Fired,"Why the Truth Might Get You Fired October 29, ...",1
3,15 Civilians Killed In Single US Airstrike Hav...,Videos 15 Civilians Killed In Single US Airstr...,1
4,Iranian woman jailed for fictional unpublished...,Print \nAn Iranian woman has been sentenced to...,1
6,Life: Life Of Luxury: Elton John’s 6 Favorite ...,Ever wonder how Britain’s most iconic pop pian...,1
...,...,...,...
20788,Maine’s Gov. LePage Threatens To ‘Investigate’...,Google Pinterest Digg Linkedin Reddit Stumbleu...,1
20791,Lawyer Who Kept Hillary Campaign Chief Out of ...,Lawyer Who Kept Hillary Campaign Chief Out of ...,1
20793,Idiot Who Destroyed Trump Hollywood Star Gets ...,Share This \nAlthough the vandal who thought i...,1
20798,"NATO, Russia To Hold Parallel Exercises In Bal...","NATO, Russia To Hold Parallel Exercises In Bal...",1
20799,What Keeps the F-35 Alive,"David Swanson is an author, activist, journa...",1

In [387]:
real_news_kaggle

,title,text,label
1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Ever get the feeling your life circles the rou...,0
5,Jackie Mason: Hollywood Would Love Trump if He...,"In these trying times, Jackie Mason is the Voi...",0
7,Benoît Hamon Wins French Socialist Party’s Pre...,"PARIS — France chose an idealistic, traditi...",0
8,Excerpts From a Draft Script for Donald Trump’...,Donald J. Trump is scheduled to make a highly ...,0
9,"A Back-Channel Plan for Ukraine and Russia, Co...",A week before Michael T. Flynn resigned as nat...,0
...,...,...,...
20792,"Jakarta Bombing Kills Three Police Officers, L...",Two suicide bombers attacked a bus station in ...,0
20794,Trump: Putin ’Very Smart’ to Not Retaliate ove...,Donald Trump took to Twitter Friday to praise ...,0
20795,Rapper T.I.: Trump a ’Poster Child For White S...,Rapper T. I. unloaded on black celebrities who...,0
20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",When the Green Bay Packers lost to the Washing...,0
20797,Macy’s Is Said to Receive Takeover Approach by...,The Macy’s of today grew from the union of sev...,0

###################

In [388]:
mcintire.drop(['id'], axis=1, inplace=True)

In [389]:
mcintire.reset_index(drop=True, inplace=True)

In [390]:
# Replace 'FAKE' with 1 and 'REAL' with 0 in the 'label' column of the 'McIntire' DataFrame
mcintire['label'] = mcintire['label'].replace({'FAKE': 1, 'REAL': 0})

In [391]:
# Append 'McIntire' DataFrame to the existing CSV files without overwriting
fake_news_mcintire = mcintire[mcintire['label'] == 1]
real_news_mcintire = mcintire[mcintire['label'] == 0]

In [392]:
fake_news_mcintire

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",1
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,1
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",1
5,"Tehran, USA","\nI’m not an immigrant, but my grandparents ...",1
6,Girl Horrified At What She Watches Boyfriend D...,"Share This Baylee Luciani (left), Screenshot o...",1
...,...,...,...
6326,DOJ COMPLAINT: Comey Under Fire Over Partisan ...,DOJ COMPLAINT: Comey Under Fire Over Partisan ...,1
6328,Radio Derb Is On The Air–Leonardo And Brazil’s...,,1
6329,Assange claims ‘crazed’ Clinton campaign tried...,Julian Assange has claimed the Hillary Clinton...,1
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,1
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,1

In [393]:
real_news_mcintire

,title,text,label
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,0
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,0
7,‘Britain’s Schindler’ Dies at 106,A Czech stockbroker who saved more than 650 Je...,0
8,Fact check: Trump and Clinton at the 'commande...,Hillary Clinton and Donald Trump made some ina...,0
9,Iran reportedly makes new push for uranium con...,Iranian negotiators reportedly have made a las...,0
...,...,...,...
6324,Alabama Lawmaker: Same-Sex Couples Don’t Deser...,Most conservatives who oppose marriage equalit...,0
6327,GOP Senator David Perdue Jokes About Praying f...,The freshman senator from Georgia quoted scrip...,0
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,0
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",0
6334,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,0

###################

In [394]:
reutersReal.drop(['subject', 'date'], axis=1, inplace=True)
reutersFake.drop(['subject', 'date'], axis=1, inplace=True)

In [395]:
reutersReal.reset_index(drop=True, inplace=True)
reutersFake.reset_index(drop=True, inplace=True)

In [396]:
reutersReal['label'] = 0
reutersFake['label'] = 1

In [397]:
# Append 'ReutersFake' and 'ReutersReal' DataFrame to the existing CSV files without overwriting
fake_news_reuters = reutersFake[reutersFake['label'] == 1]
real_news_reuters = reutersReal[reutersReal['label'] == 0]

In [398]:
fake_news_reuters

,title,text,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,1
...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,1
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,1
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,1
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,1
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,1

In [399]:
real_news_reuters

,title,text,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,0
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,0
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,0
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,0
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,0
...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,0
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",0
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,0
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,0
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,0

###################

In [400]:
buzzfeedReal.drop(['id', 'url', 'top_img', 'authors', 'source', 'publish_date', 'movies', 'images', 'canonical_link', 'meta_data'], axis=1, inplace=True)
buzzfeedFake.drop(['id', 'url', 'top_img', 'authors', 'source', 'publish_date', 'movies', 'images', 'canonical_link', 'meta_data'], axis=1, inplace=True)
politiReal.drop(['id', 'url', 'top_img', 'authors', 'source', 'publish_date', 'movies', 'images', 'canonical_link', 'meta_data'], axis=1, inplace=True)

In [401]:
buzzfeedReal.reset_index(drop=True, inplace=True)
buzzfeedFake.reset_index(drop=True, inplace=True)
politiReal.reset_index(drop=True, inplace=True)

In [402]:
buzzfeedFake['label'] = 1
buzzfeedReal['label'] = 0
politiReal['label'] = 0

In [403]:
# Append 'BuzzfeedReal', 'BuzzfeedFake' and 'PolitiReal' DataFrame to the existing CSV files without overwriting
fake_news_buzzfeed = buzzfeedFake[buzzfeedFake['label'] == 1]
real_news_buzzfeed = buzzfeedReal[buzzfeedReal['label'] == 0]
real_news_politifact = politiReal[politiReal['label'] == 0]

In [404]:
fake_news_buzzfeed

,title,text,label
0,Proof The Mainstream Media Is Manipulating The...,I woke up this morning to find a variation of ...,1
1,Charity: Clinton Foundation Distributed “Water...,Former President Bill Clinton and his Clinton ...,1
2,A Hillary Clinton Administration May be Entire...,After collapsing just before trying to step in...,1
3,Trump’s Latest Campaign Promise May Be His Mos...,"Donald Trump is, well, deplorable. He’s sugges...",1
4,Website is Down For Maintenance,Website is Down For Maintenance,1
...,...,...,...
86,Hillary’s TOP Donor Country Just Auctioned Off...,Hillary’s TOP Donor Country Just Auctioned Off...,1
87,Cavuto Just Exposed Lester Holt's Lies During ...,Advertisement - story continues below\n\nThe f...,1
88,"The AP, In 2004, Said Your Boy Obama Was BORN ...",Well THAT’S Weird. If the Birther movement is ...,1
89,People Noticed Something Odd About Hillary's O...,\n\nThere’s a lot to be discussed about last n...,1
90,People Noticed Something Odd About Hillary’s O...,People Noticed Something Odd About Hillary’s O...,1

In [405]:
real_news_buzzfeed

,title,text,label
0,Another Terrorist Attack in NYC…Why Are we STI...,"On Saturday, September 17 at 8:30 pm EST, an e...",0
1,"Donald Trump: Drugs a 'Very, Very Big Factor' ...",Less than a day after protests over the police...,0
2,"Obama To UN: ‘Giving Up Liberty, Enhances Secu...","Obama To UN: ‘Giving Up Liberty, Enhances Secu...",0
3,Trump vs. Clinton: A Fundamental Clash over Ho...,Getty Images Wealth Of Nations Trump vs. Clint...,0
4,"President Obama Vetoes 9/11 Victims Bill, Sett...",President Obama today vetoed a bill that would...,0
...,...,...,...
86,It’s “Trump is HITLER” Month at the Washington...,"Like much of the mainstream media, the Washing...",0
87,Obama’s team isn’t laughing at Trump anymore,2016 Obama’s team isn’t laughing at Trump anym...,0
88,"Georgia poll: Donald Trump, Hillary Clinton in...","Story highlights Trump has 45%, Clinton 42% an...",0
89,Chelsea Handler Gets The Last Word After RNC C...,There may be a few women out there who enjoy a...,0
90,Is Donald Trump qualified to be president?,Off Message Is Donald Trump qualified to be pr...,0

In [406]:
real_news_politifact

,title,text,label
0,Trump Just Insulted Millions Who Lost Everythi...,16.8k SHARES SHARE THIS STORY\n\nHillary Clint...,0
1,Famous dog killed in spot she waited a year fo...,Famous dog killed in spot she waited a year fo...,0
2,House oversight panel votes Clinton IT chief i...,Story highlights The House Oversight panel vot...,0
3,America Just Tragically Lost A Country Music I...,We are absolutely heartbroken to hear about th...,0
4,Monuments to the Battle for the New South,"Nine years ago, a driver lost control of his p...",0
...,...,...,...
115,"Donald Trump, Germany’s disfavored son – POLITICO","KALLSTADT, Germany — Few places in Germany are...",0
116,BREAKING: Hollywood Legend Just Died Of Terrib...,Hollywood loses yet another one of their deare...,0
117,Worst. President. Ever.,"As my 25th wedding anniversary approached, I t...",0
118,Don King drops N-word while introducing Donald...,Story highlights Trump was sitting in a chair ...,0
119,Donald Trump Jr. Compares Syrian Refugees to S...,"Donald Trump Jr., a son of the Republican pres...",0

###################

In [407]:
welfake = pd.read_csv('WELFake/WELFake_Dataset.csv')

In [408]:
welfake

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1
...,...,...,...,...
72129,72129,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0
72130,72130,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",1
72131,72131,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
72132,72132,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,0
72133,72133,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1

In [409]:
welfake.drop(['Unnamed: 0'], axis=1, inplace=True)

In [410]:
welfake.dropna(subset=['text'], how='any', inplace=True)

In [411]:
# Filter welfake dataset based on label
fake_news_welfake = welfake[welfake['label'] == 1]  # label 1 represents fake news
real_news_welfake = welfake[welfake['label'] == 0]  # label 0 represents real news

In [412]:
fake_news_welfake.to_csv('DuplicateTest/fake_news.csv', index=False)
real_news_welfake.to_csv('DuplicateTest/real_news.csv', index=False)

In [413]:
welfake

,title,text,label
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,NaN,Did they post their votes for Hillary already?,1
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1
...,...,...,...
72129,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...,0
72130,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n...",1
72131,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...,0
72132,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...,0
72133,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...,1

In [414]:
duplicates_count = welfake.duplicated(subset=['text']).sum()
print(f"Number of duplicate entries in the 'text' column: {duplicates_count}")

Number of duplicate entries in the 'text' column: 9377